### ISSUE TITLE
I can't find the ./run-code-drop.sh

### ISSUE THREAD

**Issue by NovicecoderCrisis** [ramonfontes/p4-scenarios#2]
Hi Ramon Fontes, I am learning your repo which forked from p4-tutorial (p4+mininet wifi)(https://github.com/ramonfontes/tutorials/tree/master/exercises/). 

When I want to achieve the bssid-based, I have some trouble:
`sudo make run` is successful. but running receive.py in h4  occurs error(line 29) because ./run-code-drop.sh is not found.

I need some help! Thanks!

**Comment by ramonfontes** [comment]
Yes you're right. However, you can take https://github.com/ramonfontes/tutorials/blob/master/exercises/handover/run-code.sh as reference to run `/topo-drop` and `/topo-allow`

**Comment by NovicecoderCrisis** [comment]
OK, I understand. Thanks!
